### ISSUE TITLE
Incorrect JCasC configuration export when a JFrog CLI installation is set to "install the latest version"

### ISSUE THREAD

**Issue by jordibellido** [jenkinsci/jfrog-plugin#30]
### Describe the bug

On "Manage Jenkins -> Global Tool Configuration", I have set a JFrog CLI installation to always download the latest JFrog CLI tool available on releases.jfrog.io :
![2024-05-08-jenkinsci_jfrog-plugin-JCasC_error_latest](https://github.com/jenkinsci/jfrog-plugin/assets/14982607/3bc822f2-9bbe-4830-b5e8-6f2b378828e2)

I have reproduced this issue in three different Jenkins instances (same version, same plugins and same version plugins): if I export the JCasC configuration, the exported section for the aforementioned JFrog CLI installation is incorrect, because it just exports the installation name. When importing it back, the JFrog CLI installation is partially restored in Jenkins, because it has no information that it needs to use the latest version from JFrog repository, hence jobs using _jf_ fail with the following error:
`A 'jfrog' tool was not set. Using JFrog CLI from the system path.`

As documented in the main page from this plugin and from #7, this is the right exported configuration for this case I have tested:
```
  jfrog:
    installations:
    - name: "jfrog-cli-latest"
      properties:
      - installSource:
          installers:
          - "releasesInstaller"
```

### Current behavior

The JCasC configuration is partially exported:
```
  jfrog:
    installations:
    - name: "jfrog-cli-latest"
```

### Reproduction steps

1. Install Jenkins and the following plugins: **configuration-as-code** and **jfrog**.
2. Go to "Manage Jenkins -> Global Tool Configuration"
3. Create a new JFrog CLI installation to always download the latest JFrog CLI tool available on releases.jfrog.io. A valid test name could be _jfrog-cli-latest_.
4. Go to "Manage Jenkins -> Configuration as Code" and click on the "View Configuration" button to export the JCasC confguration.
5. Search for the string **jfrog:** to see how the related configuration was exported.

### Expected behavior

The JCasC configuration is correctly exported:
```
  jfrog:
    installations:
    - name: "jfrog-cli-latest"
      properties:
      - installSource:
          installers:
          - "releasesInstaller"
```

### JFrog plugin version

1.4.0

### JFrog CLI version

any

### Operating system type and version

AmazonLinux 2
