### ISSUE TITLE
jfrog installation as a tool on FreeBSD using incorrect binary

### ISSUE THREAD

**Issue by yannk** [jenkinsci/jfrog-plugin#37]
### Describe the bug

Following the [documentation to install the CLI ](https://plugins.jenkins.io/jfrog/) -- in my case JCasC, the tool binary installed doesn't match the FreeBSD Platform

### Current behavior

incorrect:
```
% file  /zdata/builder/tools/io.jenkins.plugins.jfrog.JfrogInstallation/jfrog-cli/jf
/zdata/builder/tools/io.jenkins.plugins.jfrog.JfrogInstallation/jfrog-cli/jf: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=E2hxi75DgIIO1RnMvoGf/IxvbmBr8BHL0vWYw-juQ/EwpAMaqXtCBUN4tZRxgr/kqhsEDeRhUTnv7HS0mq0, not stripped
```

### Reproduction steps

The tool section is defined as such:

 ```
       tool:
          jfrog:
            installations:
            - name: "jfrog-cli"
              properties:
              - installSource:
                  installers:
                  - "releasesInstaller"
```

The console log

```
/zdata/builder/tools/io.jenkins.plugins.jfrog.JfrogInstallation/jfrog-cli/jf: 1: Syntax error: word unexpected 
```

### Expected behavior

The file output should be instead something like: 

```
ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD),...
```

### JFrog plugin version

1.5.1

### JFrog CLI version

1.5.1

### Operating system type and version

FreeBSD 14.1
